version: '3'
services:
  nginx:
      build:
        context: .
        dockerfile: ./nginx/Dockerfile
      container_name: "jccoach_nginx"  
      restart: always
      volumes:
      - ./src:/var/www/html
      ports:
        - "80:80"
        - "443:443"
#      links:
#        - php-fpm
